### ISSUE TITLE
Tca fields with renderType set are treated as relations

### ISSUE THREAD

**Issue by martinhummer** [Codappix/search_core#147]
Fields like 'starttime' of table 'tt_content' have a renderType="inputDateTime".

The `RelationResolver` treats this kind of fields like a relation and returns an empty array for this kind of fields instead of indexing the timestamp in this case.
https://github.com/Codappix/search_core/blob/7cc1616d3a2d6d5734fc6deb3bfeaf1dad84168e/Classes/Domain/Index/TcaIndexer/RelationResolver.php#L85

**Comment by DanielSiepmann** [comment]
Thanks yes now I got the problem, it's not that we handle the field as relation, but that we already call the TYPO3 API which resolves the unixtimestamp to something else, which might be a date, but also could contain something like `19.06.12 (-6 yrs)`.

I think we should fix that by resolving #149. Hopefully I'm able to finish that till next week Thursday.
