### ISSUE TITLE
Make index name configurable

### ISSUE THREAD

**Issue by DanielSiepmann** [Codappix/search_core#75]
We use `typo3content` at the moment but this should be configurable.
This way it would be possible to use the same server for staging and production or multiple TYPO3 instances.

**Comment by DenisMir** [comment]
Is there a chance that a pull request would be integrated which allows to configure the index name in typoscript? We got several (>10) language variants on the site and would like to push our data into different Elasticsearch indexes depending on the sys language uid of the content.

**Comment by DanielSiepmann** [comment]
Hey @DenisMir,

of course, I would be very happy if you provide the feature. Please add necessary documentation and tests for the new feature in addition to the feature itself.

I did not think about the feature itself yet. So there might be some issues with indexing, searching and deletion through multiple indexes. I don't even know a proper way to configure that.

But let's see your solution.
